### Data representation

FMAT primarily handles two types of data (both 2d arrays): **Samples** and **Intervals**

- **Samples**: each row represents a sample of the form  
  `[sample time, value1, value2, ...]`

- **Intervals**: each row represents an interval of the form  
  `[onset time, offset time]`

In [1]:
import numpy as np
import fmatoolbox as fma

In [2]:
# define samples and intervals
spikes = np.column_stack((np.random.randn(50)*20, np.random.randint(5,size=50))) # random spike times from 5 units, not time sorted
lfp = np.column_stack((np.linspace(0,20,100), np.random.randn(100))) # random lfp signal, sorted in time
intervals = np.linspace(5,15,18)
intervals = np.column_stack((intervals, intervals + np.random.rand(18))) # random overlapping intervals, sorted in time
print('spikes:'), print(spikes[:5]), print('lfp:'),  print(lfp[:5]), print('intervals:'), print(intervals[:10]);

spikes:
[[ -5.07847282   1.        ]
 [-13.05745143   3.        ]
 [ 34.83595561   3.        ]
 [-15.98755244   4.        ]
 [ -0.27280027   4.        ]]
lfp:
[[ 0.          0.53397664]
 [ 0.2020202  -1.78845775]
 [ 0.4040404   0.16432768]
 [ 0.60606061 -0.54461052]
 [ 0.80808081 -0.93832525]]
intervals:
[[ 5.          5.65307975]
 [ 5.58823529  6.12533251]
 [ 6.17647059  7.06556443]
 [ 6.76470588  7.54447676]
 [ 7.35294118  7.56972174]
 [ 7.94117647  8.40037769]
 [ 8.52941176  8.73273438]
 [ 9.11764706  9.75838725]
 [ 9.70588235  9.8731891 ]
 [10.29411765 11.13250685]]


In [3]:
# remove overlap in intervals
intervals = fma.general.consolidateIntervals(intervals)
print(intervals)

[[ 5.          6.12533251]
 [ 6.17647059  7.56972174]
 [ 7.94117647  8.40037769]
 [ 8.52941176  8.73273438]
 [ 9.11764706  9.8731891 ]
 [10.29411765 11.13250685]
 [11.47058824 13.50996958]
 [13.82352941 14.27817157]
 [14.41176471 14.71339463]
 [15.         15.51632725]]


In [4]:
# find spikes in intervals
fma.general.restrict(spikes,intervals)

array([[ 7.51767542,  1.        ],
       [ 6.60484337,  3.        ],
       [ 5.68975042,  4.        ],
       [ 6.42496994,  3.        ],
       [13.06179354,  3.        ]])

In [ ]:
# PETH of LFP around spike times
_, t, peth = fma.analysis.PETH(lfp,spikes[:,0])

In [ ]:
# shuffle spikes per unit (assumes spikes is time sorted)
fma.general.shuffleEvents(spikes)

array([[-86.56998739,   1.        ],
       [-85.9745796 ,   1.        ],
       [-72.94270577,   1.        ],
       [-69.57251947,   1.        ],
       [-65.74316501,   1.        ],
       [-65.18962429,   1.        ],
       [-65.00214936,   1.        ],
       [-62.55094339,   1.        ],
       [-61.69818923,   1.        ],
       [-46.39493472,   1.        ],
       [-44.6269598 ,   1.        ],
       [-43.57490203,   1.        ],
       [-20.27669455,   3.        ],
       [-16.74687783,   1.        ],
       [-14.90367024,   4.        ],
       [-12.82227894,   2.        ],
       [ -7.74495461,   3.        ],
       [ -3.64607471,   2.        ],
       [ -1.33138767,   4.        ],
       [ -0.16078979,   2.        ],
       [  2.426579  ,   2.        ],
       [  3.65402244,   1.        ],
       [  3.81406703,   2.        ],
       [  4.21990035,   3.        ],
       [  4.94773271,   4.        ],
       [  7.15714254,   4.        ],
       [  8.58801674,   4.        ],
 