### Data representation

FMAT primarily handles two types of data (both 2d arrays): **Samples** and **Intervals**

- **Samples**: each row represents a sample of the form  
  `[sample time, value1, value2, ...]`

- **Intervals**: each row represents an interval of the form  
  `[onset time, offset time]`

In [1]:
import numpy as np
import fmatoolbox as fma

In [2]:
# define samples and intervals
spikes = np.column_stack((np.random.randn(50)*20, np.random.randint(5,size=50))) # random spike times from 5 units, not time sorted
lfp = np.column_stack((np.linspace(0,20,100), np.random.randn(100))) # random lfp signal, sorted in time
intervals = np.linspace(5,15,18)
intervals = np.column_stack((intervals, intervals + np.random.rand(18))) # random overlapping intervals, sorted in time
print('spikes:'), print(spikes[:5]), print('lfp:'),  print(lfp[:5]), print('intervals:'), print(intervals[:10]);

spikes:
[[  8.19858544   2.        ]
 [ 23.03960251   2.        ]
 [-23.49041375   2.        ]
 [-41.76366499   1.        ]
 [ 18.63079159   0.        ]]
lfp:
[[ 0.          1.53902066]
 [ 0.2020202   1.31019364]
 [ 0.4040404  -1.09594175]
 [ 0.60606061 -0.3032426 ]
 [ 0.80808081  0.40731601]]
intervals:
[[ 5.          5.03838032]
 [ 5.58823529  5.82073826]
 [ 6.17647059  6.1934562 ]
 [ 6.76470588  6.80030728]
 [ 7.35294118  7.43093312]
 [ 7.94117647  8.13674258]
 [ 8.52941176  9.27103585]
 [ 9.11764706  9.93629025]
 [ 9.70588235 10.14758773]
 [10.29411765 10.34035898]]


In [3]:
# remove overlap in intervals
intervals = fma.general.consolidateIntervals(intervals)
print(intervals)

[[ 5.          5.03838032]
 [ 5.58823529  5.82073826]
 [ 6.17647059  6.1934562 ]
 [ 6.76470588  6.80030728]
 [ 7.35294118  7.43093312]
 [ 7.94117647  8.13674258]
 [ 8.52941176 10.14758773]
 [10.29411765 10.34035898]
 [10.88235294 11.09737366]
 [11.47058824 12.05546213]
 [12.05882353 12.61481393]
 [12.64705882 12.66361462]
 [13.23529412 14.23234567]
 [14.41176471 14.53492944]
 [15.         15.96169951]]


In [4]:
# find spikes in intervals
fma.general.restrict(spikes,intervals)

array([[10.05171839,  1.        ],
       [ 9.46217975,  4.        ],
       [11.98210767,  2.        ],
       [11.09040878,  4.        ],
       [ 9.02039551,  3.        ],
       [ 9.00828522,  0.        ],
       [ 8.55367861,  2.        ]])

In [ ]:
# PETH of LFP around spike times
_, t, peth = fma.analysis.PETH(lfp,spikes[:,0])

In [ ]:
# shuffle spikes per unit (assumes spikes is time sorted)
fma.general.shuffleEvents(spikes)

array([[-86.56998739,   1.        ],
       [-85.9745796 ,   1.        ],
       [-72.94270577,   1.        ],
       [-69.57251947,   1.        ],
       [-65.74316501,   1.        ],
       [-65.18962429,   1.        ],
       [-65.00214936,   1.        ],
       [-62.55094339,   1.        ],
       [-61.69818923,   1.        ],
       [-46.39493472,   1.        ],
       [-44.6269598 ,   1.        ],
       [-43.57490203,   1.        ],
       [-20.27669455,   3.        ],
       [-16.74687783,   1.        ],
       [-14.90367024,   4.        ],
       [-12.82227894,   2.        ],
       [ -7.74495461,   3.        ],
       [ -3.64607471,   2.        ],
       [ -1.33138767,   4.        ],
       [ -0.16078979,   2.        ],
       [  2.426579  ,   2.        ],
       [  3.65402244,   1.        ],
       [  3.81406703,   2.        ],
       [  4.21990035,   3.        ],
       [  4.94773271,   4.        ],
       [  7.15714254,   4.        ],
       [  8.58801674,   4.        ],
 